---
exclude: ^(ve/|venv/|sidekickvenv/)
repos:
  - repo: https://github.com/ambv/black
    rev: 1fbf7251ccdb58ba93301622388615633ecc348a
    hooks:
      - id: black
        language_version: python3.9
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: flake8
        types: [python]
        additional_dependencies: ['flake8-print']

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.16.0
    hooks:
      - id: yamllint
        files: ^.*\.(yml|yaml)$

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
      - id: isort
