---
language: python

env:
  global:
    - REGISTRY_USER=rapidproautomation
    - secure: "t8wSKscPM83UejJc0sxlGzC2ieKilwfeTY3aaSrW52O+O/B3Sl2RGWtWQ6zwvu8o87/9yCF2daMxVc5OQe9T7dMbykL+lo7h1GjPW6qFEqSs0L3yHJOJAzMbNwSraADYiWl0ExGP7v44Q0hJli1CRgK9DIyWPATmw9tgMa7qtc//4uSvl4kppejVb5H3IuvPnLhu/cXSrKF/1ms7mmx9c4/slDI/5c65A2tACMK+3nit8Sz3z33NzfJtjnIO6C0FnEgmljdJ+Hf9O3fYqkNaB03jEmmFmNm5rgMA6hrOhqN1Dh8SfZws2LgJW5aWBLejpTlXIp145uAWr0FOZkfMRQUVX5qYnmwZ5WxzmhhgrKQNLr56S6St2k//6077dEIw2neLrT1oLj4HaG/9ewrm5qaQON3QF/RCZ2vEbzUxthQPfPKKxOAgJrBV5p64UM4gzS87sS6jMUMMCvcltppK21iLLinRE3FwqyBFCnrA03TyVXWGnib/eR0b8kFul5fOtga/qKAeeoW+IHVBWhy7O4f16GdxA3VuV1WY+w2v+CzH94Yrvged3msWbvsQXlePf4W2op86Xu8Bqoxl2ghlahOqgnUEKY4OU20Xpwy13tr5aZIM4qDvFoHw7NQ6/fWcyykfSIfb4YeS1+CpBAxCZZUUpGtMt3WPYzjP2FbPlaY="   # yamllint disable-line

matrix:
  include:
    - python: '3.6'
      addons:
        postgresql: '9.4'
      services:
        - postgresql
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-dev.txt --no-cache-dir
        # temporary until there is a new PyCap Release
        - pip install git+git://github.com/redcap-tools/PyCap.git@d9d3dea68640920eefb5d5d095cc62d2968c202d   # yamllint disable-line
        - pip install codecov
      before_script:
        - psql -U postgres -c "CREATE DATABASE rp_sidekick;"
      script:
        - black --check .
        - isort -c -rc .
        - flake8
        - py.test --cov=./ --color=yes
        - python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)   # yamllint disable-line
      after_success:
        - codecov

    - python: '3.6'
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - IMAGE_NAME=praekeltfoundation/rp-sidekick:develop
      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .
      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin   # yamllint disable-line
      deploy:
        provider: script
        script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"   # yamllint disable-line
        on:
          branch: develop
      install: []
      addons: {}
    - python: '3.6'
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - IMAGE_NAME=praekeltfoundation/rp-sidekick
      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .
      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin   # yamllint disable-line
      deploy:
        provider: script
        script: dcd --version "$(git tag -l --points-at HEAD)" --version-semver --version-latest "$IMAGE_NAME"   # yamllint disable-line
        on:
          tags: true
      install: []
      addons: {}
