language: python
python:
  - '3.6'
addons:
  postgresql: '9.4'
services:
  - postgresql
install:
  - pip install -r requirements.txt --use-wheel
  - pip install -r requirements-dev.txt --use-wheel
script:
  - flake8
  - py.test
  - python manage.py makemigrations rp_redcap --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
matrix:
  include:
    - python: '2.7'
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - IMAGE_NAME=praekeltfoundation/rp-sidekick:develop
        - REGISTRY_USER=rapidproautomation
        # REGISTRY_PASS
        - secure: "OaDBXKQ1MPxWh8LgQDoSkoVu0618fq1pDJeGS/+5XUtUK2tS0W1t909uZAgb7sZpieATUEel2jiRq/S41dE3FY1qNfppQaukgrjyeDQAE3I2SQKepP5+WAgC8IPZvZNwxsLNZPwbKJNL5NoLxELU2i4cvkrGf3oSAScw5A5/oL180xhyElEEvpPJGIJU0jDuF0NETeCL/pW9173ZGo5liyPgbQ9JVORglDOrMDIylO7mUO0JporZglYBgTIo9iaYXr+0SU2Lk1fs6W+9J7urjYSgxVZHYW+JS5JRtuZo8AqocH2sVIUOdY3mEBQJom8lGMpjnbUh2syLMGXB4MbsZur/9hwTDu6VqjlAnD9aGjybcX3o9ZrVSdlw3AgYMB1BS6T7Ox6hYBBBXbI16fkxBRfL95imwYjG3hPTe6OI/rq8l2pZyiR71bwVJCeSeCwF3KzR53IHtW0lZMQ2bPHKXWJ95BSdi62wb9wIYDXMGyJ4/HrWuvN17zFr2lXH97/Qmozxse0pjeBFyhzco0TVte4r4LMBoytSeUePbTusaZHn9nuecieVtLFsx5LQmU7s5N27Z4sATTOJe/vTCdFb2iVt2dmUUtk46XqHsib+wox2jCENOt4UweNof47neM3mxMgQGjkVL4w9wuNcIG+07wKMiXpGW5PGRz21JLc/Mvk="
      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .
      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      deploy:
        provider: script
        script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"
        on:
          branch: develop
      install: []
      addons: {}
    - python: '2.7'
      sudo: required
      dist: trusty
      services:
        - docker
      env:
        - IMAGE_NAME=praekeltfoundation/rp-sidekick
        - REGISTRY_USER=rapidproautomation
        # REGISTRY_PASS
        - secure: "OaDBXKQ1MPxWh8LgQDoSkoVu0618fq1pDJeGS/+5XUtUK2tS0W1t909uZAgb7sZpieATUEel2jiRq/S41dE3FY1qNfppQaukgrjyeDQAE3I2SQKepP5+WAgC8IPZvZNwxsLNZPwbKJNL5NoLxELU2i4cvkrGf3oSAScw5A5/oL180xhyElEEvpPJGIJU0jDuF0NETeCL/pW9173ZGo5liyPgbQ9JVORglDOrMDIylO7mUO0JporZglYBgTIo9iaYXr+0SU2Lk1fs6W+9J7urjYSgxVZHYW+JS5JRtuZo8AqocH2sVIUOdY3mEBQJom8lGMpjnbUh2syLMGXB4MbsZur/9hwTDu6VqjlAnD9aGjybcX3o9ZrVSdlw3AgYMB1BS6T7Ox6hYBBBXbI16fkxBRfL95imwYjG3hPTe6OI/rq8l2pZyiR71bwVJCeSeCwF3KzR53IHtW0lZMQ2bPHKXWJ95BSdi62wb9wIYDXMGyJ4/HrWuvN17zFr2lXH97/Qmozxse0pjeBFyhzco0TVte4r4LMBoytSeUePbTusaZHn9nuecieVtLFsx5LQmU7s5N27Z4sATTOJe/vTCdFb2iVt2dmUUtk46XqHsib+wox2jCENOt4UweNof47neM3mxMgQGjkVL4w9wuNcIG+07wKMiXpGW5PGRz21JLc/Mvk="
      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .
      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      deploy:
        provider: script
        script: dcd --version "$(git tag -l --points-at HEAD)" --version-semver --version-latest "$IMAGE_NAME"
        on:
          tags: true
      install: []
      addons: {}
