---
version: '3'

services:
  db:
    env_file:
      - .envs/.postgres
    image: postgres:9.6
  web:
    build: ./
    env_file: .envs/.django
    command: ./manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
