# Generated by Django 2.1.2 on 2018-11-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("rp_transferto", "0001_add_msidn_information_cache")]

    operations = [
        migrations.AlterModelOptions(
            name="msisdninformation", options={"get_latest_by": "timestamp"}
        )
    ]
