# Generated by Django 2.1.2 on 2019-03-13 23:11

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidekick", "0005_add_org_point_of_contact"),
        ("rp_transferto", "0003_add_transferto_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopupAttempt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sidekick_version", models.CharField(max_length=50)),
                ("msisdn", models.CharField(max_length=30)),
                ("from_string", models.CharField(max_length=200)),
                ("amount", models.IntegerField()),
                ("response", django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ("rapidpro_user_uuid", models.CharField(max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("C", "CREATED"),
                            ("W", "WAITING"),
                            ("S", "SUCEEDED"),
                            ("F", "FAILED"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topup_attempts",
                        to="sidekick.Organization",
                    ),
                ),
            ],
            options={"get_latest_by": "timestamp"},
        )
    ]
