# Generated by Django 4.2.11 on 2024-04-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rp_transferto", "0004_add_topup_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msisdninformation",
            name="data",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="topupattempt",
            name="response",
            field=models.JSONField(null=True),
        ),
    ]
