# Generated by Django 3.2.18 on 2023-04-03 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sidekick', '0010_modify-consent-body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmac_secret', models.CharField(blank=True, max_length=255)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidekick.organization')),
            ],
        ),
    ]
