# Generated by Django 3.2.18 on 2023-04-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_interceptors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interceptor',
            name='channel_uuid',
            field=models.CharField(default='', help_text='The uuid of the WhatsApp channel in RapidPro that should receive messages', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interceptor',
            name='hmac_secret',
            field=models.CharField(blank=True, help_text='The secret for the webhook in Turn that calls this', max_length=255),
        ),
    ]
