# Generated by Django 2.1 on 2018-08-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_redcap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='active',
        ),
        migrations.AddField(
            model_name='survey',
            name='check_fields',
            field=models.BooleanField(default=False),
        ),
    ]
