# Generated by Django 2.1 on 2018-08-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_redcap", "0002_auto_20180813_1034")]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                ("token", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="survey", name="sequence", field=models.IntegerField(default=1)
        ),
        migrations.AlterField(
            model_name="contact", name="record_id", field=models.IntegerField()
        ),
        migrations.AlterField(
            model_name="survey", name="name", field=models.CharField(max_length=200)
        ),
        migrations.AddField(
            model_name="contact",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="rp_redcap.Project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="survey",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to="rp_redcap.Project",
            ),
            preserve_default=False,
        ),
    ]
