# Generated by Django 2.1 on 2018-08-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_redcap", "0005_project_org")]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="ignore_fields",
            field=models.TextField(null=True),
        )
    ]
