# Generated by Django 2.1 on 2018-08-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_redcap", "0007_surveyanswer")]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="ignore_fields",
            field=models.TextField(blank=True, null=True),
        )
    ]
