# Generated by Django 2.1 on 2018-08-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_redcap", "0009_project_reminder_limit")]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="description",
            field=models.CharField(default="REPLACEME", max_length=200),
            preserve_default=False,
        )
    ]
