# Generated by Django 2.1 on 2018-08-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_redcap", "0010_survey_description")]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="surname",
            field=models.CharField(max_length=200, null=True),
        )
    ]
