# Generated by Django 2.1 on 2018-08-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("rp_redcap", "0011_contact_surname")]

    operations = [
        migrations.RemoveField(model_name="project", name="reminder_limit")
    ]
