# Generated by Django 2.1 on 2018-10-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_redcap", "0014_hospital_patientrecord_patientvalue")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="crf_token",
            field=models.CharField(max_length=200, null=True),
        )
    ]
