# Generated by Django 2.1 on 2018-10-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_redcap", "0015_project_crf_token")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="post_operation_fields",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="pre_operation_fields",
            field=models.TextField(null=True),
        ),
    ]
