# Generated by Django 2.1 on 2018-10-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_redcap", "0016_add_pre_and_post_op_fields")]

    operations = [
        migrations.RemoveField(model_name="patientrecord", name="status"),
        migrations.AddField(
            model_name="patientrecord",
            name="post_operation_status",
            field=models.CharField(
                choices=[
                    ("0", "Incomplete"),
                    ("1", "Unverified"),
                    ("2", "Complete"),
                ],
                default="0",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="patientrecord",
            name="pre_operation_status",
            field=models.CharField(
                choices=[
                    ("0", "Incomplete"),
                    ("1", "Unverified"),
                    ("2", "Complete"),
                ],
                default="0",
                max_length=1,
            ),
        ),
    ]
