# Generated by Django 2.1 on 2018-10-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_redcap", "0017_split_patient_status_field")]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="nomination_urn",
            field=models.CharField(blank=True, max_length=200, null=True),
        )
    ]
