# Generated by Django 2.1 on 2018-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_redcap", "0018_alter_nomination_urn")]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="hospital_lead_name",
            field=models.CharField(default="replaceme", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hospital",
            name="nomination_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
