# Generated by Django 2.1 on 2018-10-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("rp_redcap", "0019_lead_and_nomination_name")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable("hospital", "rp_asos_hospital"),
                migrations.AlterModelTable(
                    "patientrecord", "rp_asos_patientrecord"
                ),
                migrations.AlterModelTable(
                    "patientvalue", "rp_asos_patientvalue"
                ),
            ],
            state_operations=[
                migrations.RemoveField(model_name="hospital", name="project"),
                migrations.RemoveField(
                    model_name="patientrecord", name="project"
                ),
                migrations.RemoveField(
                    model_name="patientvalue", name="patient"
                ),
                migrations.DeleteModel(name="Hospital"),
                migrations.DeleteModel(name="PatientRecord"),
                migrations.DeleteModel(name="PatientValue"),
            ],
        )
    ]
