# Generated by Django 4.2.20 on 2025-03-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('code', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('province', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('area_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('unit_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('district', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('municipality', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['value'], name='momconnect__value_9a1252_idx')],
            },
        ),
    ]
