# Generated by Django 4.2.16 on 2025-01-09 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sidekick", "0014_organization_contentrepo_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TurnAlerts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hmac_secret",
                    models.CharField(
                        blank=True,
                        help_text="The secret for the Turn Journey",
                        max_length=255,
                    ),
                ),
                (
                    "journey_id",
                    models.CharField(
                        default="00000",
                        help_text="The id of the Turn journey",
                        max_length=255,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        default=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sidekick.organization",
                    ),
                ),
            ],
        ),
    ]
