# Generated by Django 4.2.16 on 2025-01-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TurnAlerts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whatsappid", models.CharField(default="00000", max_length=25)),
                ("assigned_to", models.UUIDField(blank=True, null=True)),
                ("author_id", models.UUIDField(blank=True, null=True)),
                ("chat_id", models.UUIDField(blank=True, null=True)),
                ("conversation_id", models.TextField(blank=True, null=True)),
                ("message_status", models.TextField(blank=True, null=True)),
                ("message_direction", models.TextField(blank=True, null=True)),
                ("message_body", models.TextField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=15, null=True)),
                ("error_data", models.TextField(blank=True, null=True)),
                ("fallback_channel", models.TextField(blank=True, null=True)),
                ("message_type", models.TextField(blank=True, null=True)),
                ("labels", models.CharField(blank=True, max_length=25, null=True)),
                ("state", models.CharField(blank=True, max_length=25, null=True)),
                (
                    "state_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("permalink", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
