# Generated by Django 4.2.16 on 2025-01-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("turn_alerts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turnalerts",
            name="hmac_secret",
        ),
    ]
