# Generated by Django 4.2.16 on 2025-01-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("turn_alerts", "0002_remove_turnalerts_hmac_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turnalerts",
            name="org",
        ),
    ]
