# Generated by Django 4.2.16 on 2025-01-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidekick", "0014_organization_contentrepo_token_and_more"),
        ("turn_alerts", "0003_remove_turnalerts_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="turnalerts",
            name="error_code",
            field=models.CharField(
                default="00000",
                help_text="The error code that starts an event",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="turnalerts",
            name="org",
            field=models.ForeignKey(
                default=100,
                on_delete=django.db.models.deletion.CASCADE,
                to="sidekick.organization",
            ),
        ),
    ]
