# Generated by Django 4.2.16 on 2025-01-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turn_alerts", "0004_turnalerts_error_code_turnalerts_org"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turnalerts",
            name="error_code",
            field=models.IntegerField(
                default="00000",
                help_text="The error code that starts an event",
                max_length=255,
            ),
        ),
    ]
