# Generated by Django 4.2.16 on 2025-01-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sidekick", "0014_organization_contentrepo_token_and_more"),
        ("turn_alerts", "0005_alter_turnalerts_error_code"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TurnAlerts",
            new_name="TurnActions",
        ),
    ]
