# Generated by Django 4.2.16 on 2025-01-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turn_alerts", "0006_rename_turnalerts_turnactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="turnactions",
            name="hmac_secret",
            field=models.CharField(
                blank=True,
                help_text="The secret for the webhook in Turn that calls this",
                max_length=255,
            ),
        ),
    ]
