# Generated by Django 4.2.16 on 2025-01-22 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidekick", "0014_organization_contentrepo_token_and_more"),
        ("turn_alerts", "0007_turnactions_hmac_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="TurnSecret",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret", models.CharField(max_length=255)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sidekick.organization",
                    ),
                ),
            ],
        ),
    ]
