# Generated by Django 4.2.16 on 2025-01-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("turn_alerts", "0008_turnsecret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turnactions",
            name="hmac_secret",
        ),
    ]
