# Generated by Django 2.2.3 on 2019-07-26 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidekick", "0010_modify-consent-body"),
        ("rp_gpconnect", "0002_contactimport_org"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Flow"),
                            ("initiation", "Initiation Flow"),
                            ("non-compliant", "Non-Compliant Flow"),
                            ("recomply", "Recomply Flow"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "rapidpro_flow",
                    models.CharField(
                        help_text="RapidPro ID of the flow to trigger", max_length=200
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flows",
                        to="sidekick.Organization",
                    ),
                ),
            ],
        )
    ]
