# Generated by Django 2.2.3 on 2019-08-04 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_gpconnect", "0003_flow")]

    operations = [
        migrations.AlterField(
            model_name="contactimport",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
