# Generated by Django 3.2.14 on 2023-09-06 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sidekick', '0010_modify-consent-body'),
    ]

    operations = [
        migrations.CreateModel(
            name='DtoneAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('apikey', models.CharField(max_length=200)),
                ('apisecret', models.CharField(max_length=200)),
                ('production', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtone_account', to='sidekick.organization')),
            ],
        ),
    ]
