# Generated by Django 3.2.14 on 2023-09-11 11:21

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidekick', '0010_modify-consent-body'),
        ('rp_dtone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('msisdn', models.CharField(max_length=30)),
                ('value', models.IntegerField()),
                ('operator_id', models.IntegerField(null=True)),
                ('product_id', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('operator_not_found', 'Operator not found'), ('product_not_found', 'Product not found'), ('error', 'Error'), ('success', 'Success')], default='created', max_length=20)),
                ('response', models.JSONField(null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_attempts', to='sidekick.organization')),
            ],
        ),
    ]
