# Generated by Django 2.1.7 on 2019-04-29 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_asos", "0002_hospital_whatsapp_group_id")]

    operations = [
        migrations.CreateModel(
            name="ScreeningRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.CharField(max_length=30)),
                ("date", models.DateField()),
                ("week_day_1", models.IntegerField(blank=True, null=True)),
                ("week_day_2", models.IntegerField(blank=True, null=True)),
                ("week_day_3", models.IntegerField(blank=True, null=True)),
                ("week_day_4", models.IntegerField(blank=True, null=True)),
                ("week_day_5", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_records",
                        to="rp_asos.Hospital",
                    ),
                ),
            ],
        )
    ]
