# Generated by Django 2.1.7 on 2019-04-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_asos", "0004_add_tz_code_to_hospital")]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="is_active",
            field=models.BooleanField(default=True),
        )
    ]
