# Generated by Django 2.1.7 on 2019-05-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("rp_asos", "0005_add_is_active_to_hospital")]

    operations = [
        migrations.AddField(
            model_name="patientrecord",
            name="hospital",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="rp_asos.Hospital",
            ),
        )
    ]
