# Generated by Django 2.1.7 on 2019-05-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_asos", "0006_add_hospital_to_patientrecord")]

    operations = [
        migrations.AddField(
            model_name="screeningrecord",
            name="total_eligible",
            field=models.IntegerField(blank=True, null=True),
        )
    ]
