# Generated by Django 2.1.7 on 2019-05-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_asos", "0008_remove_day_fields_from_screening_record")]

    operations = [
        migrations.AlterField(
            model_name="screeningrecord",
            name="date",
            field=models.DateField(null=True),
        )
    ]
