# Generated by Django 2.1.7 on 2019-05-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rp_asos", "0009_update_date_on_patient_record")]

    operations = [
        migrations.AddField(
            model_name="screeningrecord",
            name="week_1_case_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screeningrecord",
            name="week_2_case_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screeningrecord",
            name="week_3_case_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screeningrecord",
            name="week_4_case_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
