# Generated by Django 2.1 on 2018-08-16 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sidekick", "0001_create_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="users",
            field=models.ManyToManyField(
                related_name="org_users", to=settings.AUTH_USER_MODEL
            ),
        )
    ]
