# Generated by Django 2.1 on 2018-09-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sidekick", "0003_add_engage_creds")]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="engage_url",
            field=models.URLField(null=True),
        )
    ]
