# Generated by Django 2.1.2 on 2018-12-11 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0009_alter_user_last_name_max_length"),
        ("sidekick", "0004_increase_engage_token_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCredentials",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(max_length=255, null=True)),
                ("refresh_token", models.CharField(max_length=255, null=True)),
                ("token_uri", models.CharField(max_length=255, null=True)),
                ("client_id", models.CharField(max_length=255, null=True)),
                ("client_secret", models.CharField(max_length=255, null=True)),
                ("scopes", models.TextField(null=True)),
            ],
        )
    ]
