# Generated by Django 2.1.2 on 2019-03-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sidekick", "0004_increase_engage_token_size")]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="point_of_contact",
            field=models.EmailField(max_length=254, null=True),
        )
    ]
