# Generated by Django 2.1.8 on 2019-05-22 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sidekick", "0005_add_org_point_of_contact")]

    operations = [
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Human readable label describing this consent",
                        max_length=200,
                    ),
                ),
                (
                    "flow_id",
                    models.UUIDField(
                        blank=True,
                        help_text="The flow to trigger when the user visits the URL",
                        null=True,
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL to redirect to when the user visits the URL",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sidekick.Organization",
                    ),
                ),
            ],
        )
    ]
