# Generated by Django 2.1.8 on 2019-05-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("sidekick", "0007_add_consent_preview_fields")]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": [
                    ("label_turn_conversation", "Can label a Turn Conversation")
                ]
            },
        )
    ]
