# Generated by Django 2.1.8 on 2019-05-31 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("sidekick", "0008_label_turn_conversation_permission")]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": [
                    ("label_turn_conversation", "Can label a Turn Conversation"),
                    ("archive_turn_conversation", "Can archive a Turn Conversation"),
                ]
            },
        )
    ]
