# Generated by Django 2.1.8 on 2019-06-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sidekick", "0009_archive_turn_conversation_permission")]

    operations = [
        migrations.RemoveField(model_name="consent", name="body_text"),
        migrations.AddField(
            model_name="consent",
            name="body",
            field=models.TextField(
                blank=True,
                help_text="The HTML body to display to the user while redirecting. Not escaped",
            ),
        ),
    ]
