# Generated by Django 3.2.21 on 2023-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidekick', '0011_organization_filter_rapidpro_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='filter_rapidpro_fields',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
