# Generated by Django 3.2.21 on 2023-09-27 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidekick', '0012_alter_organization_filter_rapidpro_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('minimum_count', models.IntegerField(default=0)),
                ('triggered', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_monitors', to='sidekick.organization')),
            ],
        ),
    ]
